### PR TITLE
Add support for unflatten function

### LINKED ISSUE #8: Feature: Unflatten
Any thought to finish the package and add 'unflatten'?

### PR DESCRIPTION
**Pull request by Pana-g**
Closes #8

### CODE REVIEW

**Review by EduardoSaavedra — APPROVED** [review]

**Comment by danilofuchs** [comment]
Hi! Thanks for your PR, just got around to look at it. I will add some tests and get it merged/published!

**Comment by danilofuchs** [comment]
Hi @Pana-g!
I ported the relevant test cases from https://github.com/hughsk/flat/blob/master/test/test.js

I decided to not support nested maps for now:

```dart
{a.b: 123, a: {c: 321}}
```

There is one failing test for a map inside a list:

```dart
test.0.a: 123
```

Are you available to take a look?

**Comment by Pana-g** [comment]
Hi @danilofuchs ! Thanks for the feedback! Indeed there were some issues with the `unflatten` function, I also found some issues in some of the tests and fixed them as well!

**Comment by danilofuchs** [comment]
Great!
I added a check to disallow nested maps at all. I'll generate a release

**Review by danilofuchs — APPROVED** [review]

**Comment by danilofuchs** [comment]
Released!

**Pull request merged**
